import './globals.scss'
import { Archivo } from 'next/font/google'
import { GlobalContextProvider } from './Context/store'

const archivo = Archivo({ subsets: ['latin'] })

export const metadata = {
    title: 'Samurai King Resting',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={archivo.className}>
                <GlobalContextProvider>{children}</GlobalContextProvider>
            </body>
        </html>
    )
}
